name: volunteer_matching_app
description: 志愿者匹配应用，集成GeoHash、高德地图和ARKit功能

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.1.1
  
  # 网络请求
  dio: ^5.3.2
  http: ^1.1.0
  
  # 高德地图
  amap_flutter_map: ^3.0.0
  amap_flutter_location: ^3.0.0
  
  # AR功能
  ar_flutter_plugin: ^0.7.3
  
  # 权限管理
  permission_handler: ^11.0.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 工具类
  geolocator: ^10.1.0
  geohash: ^1.0.2
  
  # 语音识别
  speech_to_text: ^6.6.0
  
  # 音频播放
  audioplayers: ^5.2.1
  
  # UI组件
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/3d_models/
    - assets/ar_assets/ 